#  MEG Quality Accessment Parameters Config
defaults:
  - opm: quality_config_default
  - squid: quality_config_default
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled


hydra:
  output_subdir: null
  run:
    dir: . 


# MSQM Score Weights


## weights for each metric category
category_weights:
  time_domain: 1
  frequency_domain: 1
  entropy: 1
  fractal: 1
  artifacts: 1

